### ISSUE TITLE
Fetch feeds from a list of sources

### ISSUE THREAD

**Issue by skreutzer** [csensemakers/lib-protocol-experiments#1]
Build a mechanism that fetches the feed as controlled by a list of feed sources. Fetching should be repeatable, under the assumption this component could fetch from sources in a regular interval, for example daily or weekly.

It is OK to initially just store the obtained resource/feed as-is. What should be included however is the handling of errors, like the fetcher being offline, or a source to fetch is not reachable or responding. The result of the request/retrieval-attempt should be stored somehow, so it is indicated if the fetch of a source from the list was successful or failed.

**Comment by ronentk** [comment]
What rule are you imagining to create the aggregate feed? Chronological order?

Perhaps also worth opening an issue about aggregation more generally
https://docs.murmurations.network/about/common-terms.html#aggregator

For example instead of a feed I may want to display all books with their average rating etc

**Comment by skreutzer** [comment]
Made GitHub Issue #8. For this Issue's topic of the "fetcher", keeping both somewhat separate would allow to re-use the same code or component (or concept) for both, by an aggregator as well as in a client, reader, agent.
