### ISSUE TITLE
Specify Bookmark node

### ISSUE THREAD

**Issue by ronentk** [csensemakers/lib-protocol-experiments#9]
Based on [this](https://github.com/csensemakers/lib-protocol-experiments/issues/4#issuecomment-1378458121) discussion in #4 

Possible fields (inspired by Goodreads):
- Target URL
- Tags for categorizing content by topics
- Reading status (`want-to-read`, `finished`, `did-not-finish`, etc)
- Rating (numerical scale)
- Review (free text)

**Comment by skreutzer** [comment]
What is the purpose, meaning, function of a Bookmark? To me, it seems, Library JSON:

- has a target URL (potentially)
- current use of Library JSON seems to suggest using arbitrary lists to group books according to, for example, "Books Read". It's true that their naming/meaning is arbitrary and expressed in prose.
- has a `notes` field in the objects inside `books`

Are you suggesting:

- tagging of topics of a book's content should be added (will likely lead to follow-up GitHub Issues for how to control and UI-/tool-wise support tagging activities)
- additionally, or as a replacement, specific/controlled/semantic indicators should be used, to which kind of "list" a book belongs to, or what type of list it is, instead of relying on prose (if replacing and not additional, this might potentially limit the support for creating arbitrary lists of books which can be used for many purposes, but also reader code might not be aware of many of these)
- rating should be added

Realizing some of this is somewhat equivalent to Library JSON's semantics. How is a Bookmark different from Library JSON? Given a Bookmark data record also would need to be published by people on their Web-sites. Is Bookmark here more of a proposal for an (internal) database entity, or (conceptual) semantics to eventually build/support in the future, or a UI + use case description, or is it a proposal to change/extend the existing Library JSON format?

**Comment by skreutzer** [comment]
Not doing anything special nor clever, very simple:
```json
{
    "annotation":
    {
        "version": "0.1",
        "url": "https://example.org",
        "note": "It’s an example page purely for demonstration purposes."
    }
}
```
Is not exactly a "bookmark" as such as intended/described per the initial request, but a simple, generic annotation mechanism, to get started.
